apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vote-route
spec:
  parentRefs:
    - name: voting-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /vote
      backendRefs:
        - name: vote
          port: 80