name: CI/CD to Amazon EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Vote image
      run: |
        docker build -t shishir165/vote:v2 ./vote
        docker push shishir165/vote:v2

    - name: Build and push Result image
      run: |
        docker build -t shishir165/result:v2 ./result
        docker push shishir165/result:v2

    - name: Build and push Worker image
      run: |
        docker build -t shishir165/worker:v2 ./worker
        docker push shishir165/worker:v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Install kubectl
      uses: azure/setup-kubectl@v4

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --name my-first-eks-shishirp \
          --region eu-central-1

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/infra/
        kubectl apply -f k8s/backend/
        kubectl apply -f k8s/frontend/
        kubectl apply -f k8s/ingress.yaml